---
- name: Restart slurmctld
  ansible.builtin.systemd:
    name: slurmctld.service
    state: restarted
    enabled: true
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart slurmdbd
  ansible.builtin.systemd:
    name: slurmdbd.service
    state: restarted
    enabled: true
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart slurmd
  ansible.builtin.systemd:
    name: slurmd.service
    state: restarted
    enabled: true
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Reconfigure slurm
  ansible.builtin.command: "{{ slurm_prefix }}/{{ slurm_version }}/sbin/scontrol reconfigure"
  become: true

- name: Restart munge
  ansible.builtin.systemd:
    name: munge.service
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ...
