---
- ansible.builtin.include_tasks: hostname.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
  tags:
    - hostname

- ansible.builtin.include_tasks: packages_and_env.yml
  when:
    - "'slurm_master' in group_names"
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
  tags:
    - packages_and_env

- ansible.builtin.include_tasks: cuda.yml
  when:
    - "'slurm_master' in group_names"
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
  tags:
    - cuda

- ansible.builtin.include_tasks: pmix.yml
  when:
    - "'slurm_master' in group_names"
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
    - install_pmix
    - skip_pmix is not defined
  tags:
    - pmix

- ansible.builtin.include_tasks: munge.yml
  when:
    - "'slurm_master' in group_names"
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
  tags:
    - munge

- ansible.builtin.include_tasks: database.yml
  when:
    - "'slurm_master' in group_names"
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
    - install_database is defined
    - install_database
  tags:
    - database

- ansible.builtin.include_tasks: slurm_master.yml
  when:
    - "'slurm_master' in group_names"  
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
  tags:
    - slurm_master

- ansible.builtin.include_tasks: slurm_post_install.yml
  when:
    - "'slurm_master' in group_names"
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
  tags:
    - slurm_post_install

- ansible.builtin.include_tasks: firewall.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
    - (groups['slurm_client'] | length) > 0
  tags:
    - firewall

- ansible.builtin.include_tasks: slurm_client.yml
  when:
    - "'slurm_client' in group_names"
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
  tags:
    - slurm_client

- ansible.builtin.include_tasks: slurm_client_munge.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
    - (groups['slurm_client'] | length) > 0
  tags:
    - slurm_client_munge

- ansible.builtin.include_tasks: slurm_nfs.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8
    - (groups['slurm_client'] | length) > 0
  tags:
    - nfs

...
