---
- block:

  - name: Slurp /etc/munge/munge.key
    ansible.builtin.slurp:
      src: "/etc/munge/munge.key"
    register: slurped_munge_key
    when: inventory_hostname in groups['slurm_master']
    ignore_errors: "{{ ansible_check_mode }}"

  - name: "Set fact on client for base64decoded /etc/munge/munge.key"
    ansible.builtin.set_fact:
      munge_key_content: "{{ hostvars[item]['slurped_munge_key']['content'] | b64decode }}"
    when: inventory_hostname in groups["slurm_client"]
    loop: "{{ groups['slurm_master'] }}" #loop the 1x host within master group
    ignore_errors: "{{ ansible_check_mode }}"

  #This is always going to write... due to command usage
  - name: "Write copy of slurped_munge_key file using the slurped content - /etc/munge/munge.key"
    ansible.builtin.shell: "echo \"{{ slurped_munge_key }}\" > /etc/munge/munge.key"
    when:
      - inventory_hostname in groups["slurm_client"]
    ignore_errors: "{{ ansible_check_mode }}"
  
  - name: "Ensure perms /etc/munge/munge.key"
    ansible.builtin.file:
      path: /etc/munge/munge.key
      owner: munge
      group: munge
      mode: 0400
    when: "'slurm_client' in group_names"
    ignore_errors: "{{ ansible_check_mode }}"

  - name: Restart munge
    ansible.builtin.systemd:
      name: munge.service
      state: restarted
      enabled: true
      daemon_reload: true
    ignore_errors: "{{ ansible_check_mode }}"
    when: "'slurm_client' in group_names"
    become: true

  become: true
...
