---

- block:

  - name: install deps for slurm client
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
      - hwloc
      - hwloc-devel
      - "{{ munge_deps }}"

  # Set slurm user and group locally on every host if uid/gid given
  - name: add slurm unix group
    ansible.builtin.group: 
      name: slurm 
      system: false 
      state: present
      gid: "{{ slurm_user_uid|default(456) }}"

  - name: add slurm unix user
    ansible.builtin.user:
      name: slurm
      shell: /sbin/nologin
      createhome: false
      system: false
      append: true
      group: slurm
      state: present
      uid: "{{ slurm_user_uid|default(456) }}"

  - name: Create Slurm log directory
    ansible.builtin.file:
      state: directory
      path: "{{ slurm_log_dir }}"
      mode: 0755
      owner: slurm
      group: slurm
  
  - name: "mkdir {{ slurm_compile_prefix_dir }}"
    ansible.builtin.file:
      state: directory
      recurse: true
      path: "{{ slurm_compile_prefix_dir }}"
      owner: slurm
      group: slurm
    ignore_errors: true #may be nfs mounted already

  - name: "Create {{ slurm_prefix }}/{{ slurm_version }}/etc"
    ansible.builtin.file:
      state: directory
      path: "{{ slurm_prefix }}/{{ slurm_version }}/etc"
      mode: 0755
      owner: slurm
      group: slurm
    ignore_errors: true #may be nfs mounted already

  - name: Template slurmd systemd file
    ansible.builtin.template:
      src: "slurmd.service.j2"
      dest: /usr/lib/systemd/system/slurmd.service
      owner: slurm
      group: slurm
      mode: 0644
    notify: Restart slurmd

  - name: Ensure slurmd is running #though may not have picked up nfs mount yet for slurm.conf
    ansible.builtin.systemd:
      name: "slurmd.service"
      state: started
      enabled: true
      daemon_reload: true
    ignore_errors: true

  become: true

...
